stages:
    - build
    - deploy
build:
  stage: build
  #image: registry.parvaz.infra/docker/docker:stable
  image: nexus.parvaz.infra:4040/library/docker:stable
  script:
    - echo  ${CI_REGISTRY_IMAGE}
    - echo   ${CI_COMMIT_REF_SLUG}
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG} -f ./Dockerfile .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
  when: manual



deploy:
  stage:  deploy
  image: registry.parvaz.infra/docker/helm:latest
  before_script:
    - chmod 400 ${KUBECONFIG}
  script:
    - helm upgrade --install
      --create-namespace
      --namespace sigma
      --kubeconfig ${KUBECONFIG}
      --set registry.credentials=${REGISTRY_CRED}
      apigateway
      .chart
  when: manual
  only:
    refs:
      - Deploy
