stages:
    - build


build:
  stage: build
  #image: registry.parvaz.infra/docker/docker:stable
  image: nexus.parvaz.infra:4040/library/docker:stable
  script:
    - echo  ${CI_REGISTRY_IMAGE}
    - echo   ${CI_COMMIT_REF_SLUG}    
  when: manual