apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ include "spring-cloud-config.fullname" . }}-registry-cred
  labels:
    {{- include "spring-cloud-config.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.registry.credentials }} 